name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
    - pipeline: build_pipeline
      source: "E-Referrals-Service-API-Build"
      trigger:
        branches:
          exclude:
            - master
            - refs/heads/master
            - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_description: ${{ variables.product_description }}
    apigee_deployments:
      - environment: internal-dev
        service_name: ${{ variables.service_name }}-alpha
        short_service_name: ${{ variables.short_service_name }}-alpha
        service_base_path: ${{ variables.service_base_path }}-alpha
        stage_name: ers_alpha_pr
        jinja_templates:
          ERS_TARGET_SERVER: e-referrals-service-api--alpha
        post_deploy:
        - template: templates/ers-smoke.yml
      - environment: internal-dev-sandbox
        proxy_path: sandbox
