name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
    - pipeline: build_pipeline
      source: "E-Referrals-Service-API-Build"
      trigger:
        branches:
          include:
            - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    spec_file: ${{ variables.spec_file }}
    apigee_deployments:
    - environment: internal-dev
      stage_name: ers_alpha_live
      make_spec_visible: true
      service_name: "${{ variables.service_name }}-alpha"
      short_service_name: "${{ variables.short_service_name }}-alpha"
      product_display_name: "${{ variables.product_display_name }} (ERSALPHA)"
      service_base_path: "${{ variables.service_base_path }}-alpha"
      jinja_templates:
        ERS_TARGET_SERVER: e-referrals-service-api--alpha
    - environment: internal-dev
      stage_name: ers_rc_live
      make_spec_visible: true
      service_name: "${{ variables.service_name }}-rc"
      short_service_name: "${{ variables.short_service_name }}-rc"
      product_display_name: "${{ variables.product_display_name }} (ERSRC)"
      service_base_path: "${{ variables.service_base_path }}-rc"
      jinja_templates:
        ERS_TARGET_SERVER: e-referrals-service-api--rc
    - environment: internal-dev
      stage_name: ers_fix_live
      make_spec_visible: true
      service_name: "${{ variables.service_name }}-fix"
      short_service_name: "${{ variables.short_service_name }}-fix"
      product_display_name: "${{ variables.product_display_name }} (ERSFIX)"
      service_base_path: "${{ variables.service_base_path }}-fix"
      jinja_templates:
        ERS_TARGET_SERVER: e-referrals-service-api--fix
    - environment: internal-qa
      stage_name: ers_sa_live
      make_spec_visible: true
      service_name: "${{ variables.service_name }}-sa"
      short_service_name: "${{ variables.short_service_name }}-sa"
      product_display_name: "${{ variables.product_display_name }} (ERSSA)"
      service_base_path: "${{ variables.service_base_path }}-sa"
    - environment: internal-qa-sandbox
      proxy_path: sandbox
