name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/feature/ers-internal-dev-variants
      endpoint: NHSDigital
  pipelines:
    - pipeline: build_pipeline
      source: "E-Referrals-Service-API-Build"
      trigger:
        branches:
          exclude:
            - master
            - refs/heads/master
            - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    apigee_deployments:
      - environment: internal-dev
        service_name: ${{ variables.service_name }}-alpha
        short_service_name: ${{ variables.short_service_name }}-alpha
        service_base_path: ${{ variables.service_base_path }}-alpha
        stage_name: ers_alpha_pr
        jinja_templates:
          ERS_TARGET_SERVER: e-referrals-service-api--alpha
        post_deploy:
        - template: templates/ers-smoke.yml
      - environment: internal-dev
        service_name: ${{ variables.service_name }}-ft01
        short_service_name: ${{ variables.short_service_name }}-ft01
        service_base_path: ${{ variables.service_base_path }}-ft01
        stage_name: ers_ft01_pr
        jinja_templates:
          ERS_TARGET_SERVER: e-referrals-service-api--ft-8443
      - environment: internal-dev
        service_name: ${{ variables.service_name }}-ft04
        short_service_name: ${{ variables.short_service_name }}-ft04
        service_base_path: ${{ variables.service_base_path }}-ft04
        stage_name: ers_ft04_pr
        jinja_templates:
          ERS_TARGET_SERVER: e-referrals-service-api--ft-8444
      - environment: internal-dev
        service_name: ${{ variables.service_name }}-ft05
        short_service_name: ${{ variables.short_service_name }}-ft05
        service_base_path: ${{ variables.service_base_path }}-ft05
        stage_name: ers_ft05_pr
        jinja_templates:
          ERS_TARGET_SERVER: e-referrals-service-api--ft-8445
      - environment: internal-dev
        service_name: ${{ variables.service_name }}-ft09
        short_service_name: ${{ variables.short_service_name }}-ft09
        service_base_path: ${{ variables.service_base_path }}-ft09
        stage_name: ers_ft09_pr
        jinja_templates:
          ERS_TARGET_SERVER: e-referrals-service-api--ft-8446
      - environment: internal-dev
        service_name: ${{ variables.service_name }}-ft22
        short_service_name: ${{ variables.short_service_name }}-ft22
        service_base_path: ${{ variables.service_base_path }}-ft22
        stage_name: ers_ft22_pr
        jinja_templates:
          ERS_TARGET_SERVER: e-referrals-service-api--ft-8447
      - environment: internal-dev-sandbox
        proxy_path: sandbox
