name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
    - pipeline: build_pipeline
      source: "E-Referrals-Service-API-Build"
      trigger:
        branches:
          exclude:
            - master
            - refs/heads/master
            - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    spec_file: ${{ variables.spec_file }}
    apigee_deployments:
      - stage_name: ers_alpha
        environment: internal-dev
        service_name: ${{ variables.service_name }}-alpha
        short_service_name: ${{ variables.short_service_name }}-alpha
        service_base_path: ${{ variables.service_base_path }}-alpha
      - stage_name: ers_rc
        environment: internal-dev
        service_name: ${{ variables.service_name }}-rc
        short_service_name: ${{ variables.short_service_name }}-rc
        service_base_path: ${{ variables.service_base_path }}-rc
        depends_on:
        - ers_alpha
      - stage_name: ers_sa
        environment: internal-qa
        service_name: ${{ variables.service_name }}-sa
        short_service_name: ${{ variables.short_service_name }}-sa
        service_base_path: ${{ variables.service_base_path }}-sa
        depends_on:
        - ers_rc
