[project]
python = "^3.8"


[tool.poetry]
name = "e-referrals-service-api"
version = "0.0.1-alpha"
description = "TODO"

license = "MIT"

authors = [
]

readme = 'README.md'

repository = "https://github.com/NHSDigital/e-referrals-service-api"
homepage = ""

keywords = ["healthcare", "uk", "nhs"] #TODO add additional keywords


[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^5.2"
docopt = "^0.6.2"
jsonpath-rw = "^1.4.0"
semver = "^2.9.0"
gitpython = "^3.0.5"
lxml = "^4.9.1"
xmlformatter = "^0.2.4"
pytest-check = "^1.0.1"
requests = "^2.28.1"
openapi-core = "0.14.5"


[tool.poetry.dev-dependencies]
flake8 = "^5.0.4"
black = "^19.10b0"
pip-licenses = "^3.5.4"
jinja2 = "^2.11.1"
pytest = "^6.1.2"
pytest-asyncio = "^0.14.0"
api-test-utils = {url = "https://github.com/NHSDigital/apim-test-utils/releases/download/v1.1.31-alpha/api_test_utils-1.1.31a0-py3-none-any.whl"}

[tool.poetry.scripts]

[tool.pytest.ini_options]
markers = ["smoke_test", "integration_test", "sandbox"]
