[project]
python = "^3.8"


[tool.poetry]
name = "e-referrals-service-api"
version = "0.0.1-alpha"
description = "TODO"

license = "MIT"

authors = [
]

readme = 'README.md'

repository = "https://github.com/NHSDigital/e-referrals-service-api"
homepage = ""

keywords = ["healthcare", "uk", "nhs"] #TODO add additional keywords


[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^5.2"
docopt = "^0.6.2"
jsonpath-rw = "^1.4.0"
semver = "^3.0.1"
gitpython = "^3.1.31"
lxml = "^4.9.3"
xmlformatter = "^0.2.4"
pytest-check = "^2.1.5"
requests = "^2.31.0"
openapi-core = "0.14.2"


[tool.poetry.dev-dependencies]
flake8 = "^5.0.4"
black = "^23.3"
pip-licenses = "^4.3.2"
jinja2 = "^3.1.2"
pytest = "^6.1.2"
pytest-asyncio = "^0.14.0"
api-test-utils = {url = "https://github.com/NHSDigital/apim-test-utils/releases/download/v1.1.42-alpha/api_test_utils-1.1.42a0-py3-none-any.whl"}

[tool.poetry.scripts]

[tool.pytest.ini_options]
markers = ["smoke_test", "integration_test", "sandbox"]
