openapi: 3.0.0
x-nhsd-api-platform:
  meta:
    service_name: e-referrals-service-api
    short_service_name: ers
    service_base_path: referrals
    product_display_name: e-Referrals-Service
    product_description: The NHS e-RS vision is to enable local innovation and adoption of
      paperless referrals. To support this vision NHS Digital have created a set
      of APIs which provide a well-defined, simple to use data interface to the
      NHS e-Referral Service (e-RS). See
      https://developer.nhs.uk/apis/e-Referrals/index.html
    pipeline_name_prefix: E-Referrals-Service
tags:
  - name: api
info:
  version: 0.0.1
  title: e-Referrals Service
  description: A key aspect of the NHS e-RS vision is to enable local innovation and
    adoption of paperless referrals. To support this vision NHS Digital have
    created a set of APIs which provide a well-defined, simple to use data
    interface to the NHS e-Referral Service (e-RS).
  contact:
    email: sd.asd@nhs.uk
  license:
    name: MIT
servers:
  - url: https://api.dev3.ers.ncrs.nhs.uk/
    description: Alpha
paths:
  /v1/ProfessionalSession:
    post:
      responses:
        "201":
          description: Request accepted
          content:
            application/json:
              schema:
                $schema: http://json-schema.org/draft-04/schema#
                type: object
                properties:
                  typeInfo:
                    type: string
                  id:
                    type: string
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      identifier:
                        type: string
                      firstName:
                        type: string
                      lastName:
                        type: string
                      middleName:
                        type: "null"
                      permissions:
                        type: array
                        items:
                          - type: object
                            properties:
                              businessFunction:
                                type: string
                              orgIdentifier:
                                type: string
                              orgName:
                                type: string
                            required:
                              - businessFunction
                              - orgIdentifier
                              - orgName
                          - type: object
                            properties:
                              businessFunction:
                                type: string
                              orgIdentifier:
                                type: string
                              orgName:
                                type: string
                            required:
                              - businessFunction
                              - orgIdentifier
                              - orgName
                          - type: object
                            properties:
                              businessFunction:
                                type: string
                              orgIdentifier:
                                type: string
                              orgName:
                                type: string
                            required:
                              - businessFunction
                              - orgIdentifier
                              - orgName
                          - type: object
                            properties:
                              businessFunction:
                                type: string
                              orgIdentifier:
                                type: string
                              orgName:
                                type: string
                            required:
                              - businessFunction
                              - orgIdentifier
                              - orgName
                          - type: object
                            properties:
                              businessFunction:
                                type: string
                              orgIdentifier:
                                type: string
                              orgName:
                                type: string
                            required:
                              - businessFunction
                              - orgIdentifier
                              - orgName
                    required:
                      - identifier
                      - firstName
                      - lastName
                      - middleName
                      - permissions
                  permission:
                    type: "null"
                required:
                  - typeInfo
                  - id
                  - token
                  - user
                  - permission
      summary: A001 Create Professional Session
      description: As an e-RS user working in an integrated system I want to create a
        Professional Session in the Spine using my smartcard roles So that I can
        securely access e-RS functions through my integrated system
      parameters:
        - in: header
          name: XAPI_ASID
          schema:
            type: string
        - in: path
          name: token
          required: true
          schema:
            type: integer
            minimum: 1
          description: The user ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $schema: http://json-schema.org/draft-04/schema#
              type: object
              properties:
                typeInfo:
                  type: string
                token:
                  type: string
              required:
                - typeInfo
                - token
