# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the e-Referral Service API
# owned by NHS Digital (https://digital.nhs.uk/)
openapi: 3.0.0
x-nhsd-api-platform:
  meta:
    service_name: e-referrals-service-api
    short_service_name: ers
    service_base_path: referrals
    product_display_name: e-Referrals-Service
    product_description: 'The NHS e-RS vision is to enable local innovation and adoption of paperless referrals. To support this vision NHS Digital have created a set of APIs which provide a well-defined, simple to use data interface to the NHS e-Referral Service (e-RS). See https://developer.nhs.uk/apis/e-Referrals/index.html'
    pipeline_name_prefix: E-Referrals-Service
info:
  version: 0.0.1
  title: e-Referrals Service
  description: |
    ## Overview
    A key aspect of the NHS e-RS vision is to enable local innovation and adoption of paperless referrals. To support this vision NHS Digital have created a set of APIs which provide a well-defined, simple to use data interface to the NHS e-Referral Service (e-RS).

    You can:

    You cannot currently use this API to:

    You can read and update the following data:

    ### Access modes

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. 
    Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. 
    Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. 
    Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per 
    conubia nostra, per inceptos himenaeos. 


    ## Who can use this API

    Curabitur sodales ligula in libero. Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. 
    Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. 
    Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, 
    luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. 


    ## Related APIs

    Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. 
    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. 
    Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, 
    a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. 
    Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. 


    ## API status and roadmap

    Etiam ultrices. Suspendisse in justo eu magna luctus suscipit. Sed lectus. Integer euismod lacus luctus magna. 
    Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum 
    ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi lacinia molestie dui. 
    Praesent blandit dolor. Sed non quam. In vel mi sit amet augue congue elementum. Morbi in ipsum sit amet pede 
    facilisis laoreet. Donec lacus nunc, viverra nec, blandit vel, egestas et, augue. Vestibulum tincidunt malesuada tellus.

    ### Healthcare worker access

    Ut ultrices ultrices enim. Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper. 
    Nulla facilisi. Integer lacinia sollicitudin massa. Cras metus. Sed aliquet risus a tortor. 
    Integer id quam. Morbi mi. Quisque nisl felis, venenatis tristique, dignissim in, ultrices sit amet, 
    augue. Proin sodales libero eget ante. Nulla quam. 

    ### Citizen access

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. 
    Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. 
    Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. 
    Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per 
    conubia nostra, per inceptos himenaeos. 

    ### Roadmap

    Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. 
    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. 
    Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, 
    a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. 
    Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. 


    ## Technology

    Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. 
    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. 
    Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, 
    a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. 
    Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam.

    ## Network access

    Etiam ultrices. Suspendisse in justo eu magna luctus suscipit. Sed lectus. Integer euismod lacus luctus magna. 
    Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum 
    ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi lacinia molestie dui. 
    Praesent blandit dolor. Sed non quam. In vel mi sit amet augue congue elementum. Morbi in ipsum sit amet pede 
    facilisis laoreet. Donec lacus nunc, viverra nec, blandit vel, egestas et, augue. Vestibulum tincidunt malesuada tellus.

    ## Security and authorisation

    Ut ultrices ultrices enim. Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper. 
    Nulla facilisi. Integer lacinia sollicitudin massa. Cras metus. Sed aliquet risus a tortor. 
    Integer id quam. Morbi mi. Quisque nisl felis, venenatis tristique, dignissim in, ultrices sit amet, 
    augue. Proin sodales libero eget ante. Nulla quam. 

    ## Environments and testing

    | Environment       | Base URL                                                               |
    | ----------------- | ---------------------------------------------------------------------- |
    | Sandbox           | `https://sandbox.api.service.nhs.uk/referrals` |
    | Integration test  | `https://int.api.service.nhs.uk/referrals` |
    | Production        | `https://api.service.nhs.uk/referrals` |

    ### Sandbox testing
    Our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):
    * is for early developer testing
    * only covers a limited set of scenarios
    * is stateless, so does not actually persist any updates
    * is open access, so does not allow you to test authorisation

    Try out the sandbox using our 'Try this API' feature, see the documentation for each endpoint. Sandbox will only respond to 
    input matching one of the examples specified for each endpoint.

    ### Integration testing

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. 
    Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. 
    Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. 
    Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per 
    conubia nostra, per inceptos himenaeos. 

    ### Production smoke testing

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. 
    Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. 
    Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. 
    Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per 
    conubia nostra, per inceptos himenaeos. 

    ## Onboarding

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. 
    Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. 
    Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. 
    Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per 
    conubia nostra, per inceptos himenaeos. 


  contact:
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
  license:
    name: MIT
servers:
  - url: 'https://internal-dev-sandbox.api.service.nhs.uk/referrals-pr-14'
    description: Pr Sandbox environment.
  - url: 'https://sandbox.api.service.nhs.uk/referrals'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/referrals'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/referrals'
    description: 'Production environment.'
paths:
  /STU3/v1/ReferralRequest/$ers.createReferral:
    post:
      security:
        - bearerAuth: []
      description: |
        ## Use case
        As a Referring Clinician or Referring Clinician Administrator,
        Having identified suitable Services for my patient, I want to create a referral for my patient and associate the Referral with a list of appropriate services
        so I can initiate my Patient's referral pathway; allowing the Patient to book from one of the clinically appropriate services shortlisted.
        
        ## You can use this endpoint to
        - Create a new Referral in e-RS for a single Patient if you are a Referring Clinician or Referring Clinician Admin user.
        - Associate the Referral with a list of Services that are suitable to the patient's current care needs. This is called a "Shortlist" of Services.
        - Set a "priority" for the Referral indicating how quickly the Referral needs to be dealt with.
        - Detail the criteria used to identify suitable Services.
        - Indicate who the Referring Clinician is.
          - If you are authenticated as Referring Clinician Admin when using this endpoint, you must indicate who you the Referral is being created on behalf of. This is known as the "Referring Clinician".
        - Provide an indication as to whether or not you will add a Referrer Letter to the Referral for a Service to review.
          - This may be dependent on which services are are on your Shortlist.
          - The action of associating a Referral Letter to a Referral is completed via another endpoint.
        - Indicate if you want a reminder letter to be sent to the Patient if they don't book/defer appointment within "x" days. The reminder letter sent prompts the Patient to book their appointment.
          - "0" = no reminder letter.
          - A value of 1 to 180 can be used to set the number of days between creating the Referral and a letter being sent to the Patient.
        
        ## After successful creation of the Referral
        - The Referral can be accessed in the e-RS Professional Application or, from another endpoint.
        - Other endpoints can be used to progress or amend your Referral.
        
        ## Related endpoints
        - [A010: Patient Service Search](#api-Default-a010PatientServiceSearch) - This endpoint is used to search list of Services for the Patient.
        - [A021: Create Referral And Send For Triage](https://developer.nhs.uk/apis/e-Referrals/explore_endpoint_a021.html) - This endpoint can be used to create a Referral and sent it to a single Referral Assessment Service to asses the Referral.
        - [A020: Upload file to the e-RS document store](https://developer.nhs.uk/apis/e-Referrals/explore_endpoint_a020.html) - This endpoint is used to upload a Referral Letter.
        - [A012: Maintain Referral Letter](https://developer.nhs.uk/apis/e-Referrals/explore_endpoint_a012.html) - This endpoint is used to associate a previously uploaded document (such as a Referral Letter) to a specific Referral.

      summary: A011 Create Referral
      operationId: a011-create-referral
      parameters:
        - $ref: 'components/schemas/headers/request/BearerAuthorization.yaml'
        - $ref: 'components/schemas/headers/request/OdsCode.yaml'
        - $ref: 'components/schemas/headers/request/BusinessFunction.yaml'
        - $ref: 'components/schemas/headers/request/CorrelationID.yaml'
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: 'components/schemas/CreateReferralParameters.yaml'
            examples:
              create-referral-parameters-single-service:
                summary: Example with single service
                value:
                  $ref: 'components/examples/createReferral/requests/CreateReferralParameters.json'
              create-referral-parameters-full-search-criteria:
                summary: Example with single service and fully populated search criteria
                value:
                  $ref: 'components/examples/createReferral/requests/CreateReferralParametersFull.json'
              create-referral-parameters-twenty-services:
                summary: Example with twenty services
                value:
                  $ref: 'components/examples/createReferral/requests/CreateReferralParametersTwentyServices.json'
      responses:
        '201':
          $ref: 'components/schemas/responses/createReferral/201Response.yaml'
        '400':
          $ref: 'components/schemas/responses/BadRequest.yaml'
        '401':
          $ref: 'components/schemas/responses/Unauthorized.yaml'
        '403':
          $ref: 'components/schemas/responses/Forbidden.yaml'
        '422':
          $ref: 'components/schemas/responses/CreateReferralErrorOutcome.yaml'
        '500':
          $ref: 'components/schemas/responses/InternalServerError.yaml'
  /STU3/v1/ReferralRequest/$ers.createReferralAndSendForTriage:
    post:
      security:
        - bearerAuth: []
      description: |
        ## Use case

        ## You can use this endpoint to

        ## Related endpoints
      summary: A021 Create Referral And Send For Triage
      operationId: a021-create-referral-request-and-send-for-triage
      parameters:
        - $ref: 'components/schemas/headers/request/BearerAuthorization.yaml'
        - $ref: 'components/schemas/headers/request/OdsCode.yaml'
        - $ref: 'components/schemas/headers/request/BusinessFunction.yaml'
        - $ref: 'components/schemas/headers/request/CorrelationID.yaml'
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: 'components/schemas/CreateReferralAndSendForTriageParameters.yaml'
            examples:
              parameters:
                summary: Basic example
                value:
                  $ref: 'components/examples/createReferralAndSendForTriage/requests/Parameters.json'
              parameters-with-named-clinician:
                summary: Example with named clinician in search criteria
                value:
                  $ref: 'components/examples/createReferralAndSendForTriage/requests/ParametersWithNamedClinician.json'
      responses:
        '201':
          $ref: 'components/schemas/responses/createReferralAndSendForTriage/201Response.yaml'
        '400':
          $ref: 'components/schemas/responses/BadRequest.yaml'
        '401':
          $ref: 'components/schemas/responses/Unauthorized.yaml'
        '403':
          $ref: 'components/schemas/responses/Forbidden.yaml'
        '422':
          $ref: 'components/schemas/responses/CreateReferralErrorOutcome.yaml'
        '500':
          $ref: 'components/schemas/responses/InternalServerError.yaml'
  /STU3/v1/HealthcareService/$ers.searchHealthcareServicesForPatient:
    post:
      security:
        - bearerAuth: []
      description: |
        ## Use case

        ## You can use this endpoint to

        ## Related endpoints
      summary: A010 Patient Service Search
      operationId: a010-patient-service-search
      parameters:
        - $ref: 'components/schemas/headers/request/BearerAuthorization.yaml'
        - $ref: 'components/schemas/headers/request/OdsCode.yaml'
        - $ref: 'components/schemas/headers/request/BusinessFunction.yaml'
        - $ref: 'components/schemas/headers/request/CorrelationID.yaml'
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: 'components/schemas/PatientServiceSearchParameters.yaml'
            examples:
              parameters:
                summary: Request returning single service
                value:
                  $ref: 'components/examples/patientServiceSearch/requests/ParametersReturningSingleService.json'
              parameters-with-multiple-services-returned:
                summary: Request returning multiple services
                value:
                  $ref: 'components/examples/patientServiceSearch/requests/ParametersReturningMultipleServices.json'
              parameters-fully-populated:
                summary: Fully populated request
                value:
                  $ref: 'components/examples/patientServiceSearch/requests/ParametersFullyPopulated.json'
      responses:
        '200':
          $ref: 'components/schemas/responses/patientServiceSearch/200Response.yaml'
        '400':
          $ref: 'components/schemas/responses/BadRequest.yaml'
        '401':
          $ref: 'components/schemas/responses/Unauthorized.yaml'
        '403':
          $ref: 'components/schemas/responses/Forbidden.yaml'
        '422':
          $ref: 'components/schemas/responses/patientServiceSearch/ErrorOutcome.yaml'
        '500':
          $ref: 'components/schemas/responses/InternalServerError.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
